import type { StackDefinition } from '../types.js';

export const BUILTIN_STACKS: Record<string, StackDefinition> = {
  'frontend/react': {
    id: 'frontend/react',
    name: 'React Best Practices',
    category: 'frontend',
    description: 'React performance optimization and component composition patterns',
    tags: ['react', 'ui', 'composition'],
    origin: 'builtin',
    skills: [
      {
        name: 'vercel-react-best-practices',
        source: 'vercel-labs/agent-skills',
        subpath: 'skills/vercel-react-best-practices',
        reason: 'React component optimization and performance patterns',
      },
      {
        name: 'vercel-composition-patterns',
        source: 'vercel-labs/agent-skills',
        subpath: 'skills/vercel-composition-patterns',
        reason: 'Clean component architecture and state separation',
      },
    ],
  },
  'frontend/web-design': {
    id: 'frontend/web-design',
    name: 'Web Design & UI Polish',
    category: 'frontend',
    description: 'Web design guidelines, page transitions, and UX copy standards',
    tags: ['design', 'ui', 'ux', 'animations'],
    extends: 'frontend/react',
    origin: 'builtin',
    skills: [
      {
        name: 'web-design-guidelines',
        source: 'vercel-labs/agent-skills',
        subpath: 'skills/web-design-guidelines',
        reason: 'Visual hierarchy, typography, and responsive spacing',
      },
      {
        name: 'vercel-react-view-transitions',
        source: 'vercel-labs/agent-skills',
        subpath: 'skills/vercel-react-view-transitions',
        reason: 'Seamless animated page and element transitions',
      },
      {
        name: 'writing-guidelines',
        source: 'vercel-labs/agent-skills',
        subpath: 'skills/writing-guidelines',
        reason: 'Clear, concise user-facing copy and error messaging',
      },
    ],
  },
  'quality/review': {
    id: 'quality/review',
    name: 'Code Review & TDD',
    category: 'quality',
    description: 'Automated code review, bug diagnosis, and test-driven development',
    tags: ['quality', 'code-review', 'tdd', 'testing'],
    origin: 'builtin',
    skills: [
      {
        name: 'code-review',
        source: 'mattpocock/skills',
        subpath: 'skills/code-review',
        reason: 'Comprehensive code reviews for maintainability and bugs',
      },
      {
        name: 'diagnosing-bugs',
        source: 'mattpocock/skills',
        subpath: 'skills/diagnosing-bugs',
        reason: 'Root cause analysis and reproducible bug investigation',
      },
      {
        name: 'tdd',
        source: 'mattpocock/skills',
        subpath: 'skills/tdd',
        reason: 'Test-driven development and test coverage',
      },
    ],
  },
  'workflow/planning': {
    id: 'workflow/planning',
    name: 'Spec & Feature Planning',
    category: 'workflow',
    description: 'Design grilling, specification authoring, and spec implementation',
    tags: ['workflow', 'planning', 'spec', 'design'],
    origin: 'builtin',
    skills: [
      {
        name: 'grill-me',
        source: 'mattpocock/skills',
        subpath: 'skills/grill-me',
        reason: 'Stress-test plans and architectural decisions',
      },
      {
        name: 'to-spec',
        source: 'mattpocock/skills',
        subpath: 'skills/to-spec',
        reason: 'Turn product ideas into structured technical specs',
      },
      {
        name: 'implement-spec',
        source: 'mattpocock/skills',
        subpath: 'skills/implement-spec',
        reason: 'Deterministic step-by-step spec implementation',
      },
    ],
  },
  'workflow/architecture': {
    id: 'workflow/architecture',
    name: 'Codebase Architecture',
    category: 'workflow',
    description: 'Domain modeling, architecture improvements, and system design',
    tags: ['architecture', 'domain-modeling', 'design'],
    origin: 'builtin',
    skills: [
      {
        name: 'improve-codebase-architecture',
        source: 'mattpocock/skills',
        subpath: 'skills/improve-codebase-architecture',
        reason: 'Refactor module boundaries and dependency flow',
      },
      {
        name: 'codebase-design',
        source: 'mattpocock/skills',
        subpath: 'skills/codebase-design',
        reason: 'High-level software architecture and patterns',
      },
      {
        name: 'domain-modeling',
        source: 'mattpocock/skills',
        subpath: 'skills/domain-modeling',
        reason: 'DDD entities, value objects, and business workflows',
      },
    ],
  },
  'devops/deploy': {
    id: 'devops/deploy',
    name: 'Deployment & Git Guardrails',
    category: 'devops',
    description: 'Deployment automation, pre-commit checks, and Git guardrails',
    tags: ['devops', 'deploy', 'git', 'pre-commit'],
    origin: 'builtin',
    skills: [
      {
        name: 'deploy-to-vercel',
        source: 'vercel-labs/agent-skills',
        subpath: 'skills/deploy-to-vercel',
        reason: 'Automated deployment and preview configuration',
      },
      {
        name: 'setup-pre-commit',
        source: 'mattpocock/skills',
        subpath: 'skills/setup-pre-commit',
        reason: 'Lint and typecheck before committing',
      },
      {
        name: 'git-guardrails-claude-code',
        source: 'mattpocock/skills',
        subpath: 'skills/git-guardrails-claude-code',
        reason: 'Guardrails preventing destructive git operations',
      },
    ],
  },
  'ai/agents': {
    id: 'ai/agents',
    name: 'Agent Workflows & Handoffs',
    category: 'ai',
    description: 'Prompt authoring for agents, session handoffs, and multi-agent coordination',
    tags: ['ai', 'agents', 'prompts', 'handoff'],
    origin: 'builtin',
    skills: [
      {
        name: 'writing-for-agents',
        source: 'mattpocock/skills',
        subpath: 'skills/writing-for-agents',
        reason: 'Author clear instructions and constraints for AI agents',
      },
      {
        name: 'handoff',
        source: 'mattpocock/skills',
        subpath: 'skills/handoff',
        reason: 'Structured context handoff between agent sessions',
      },
      {
        name: 'claude-handoff',
        source: 'mattpocock/skills',
        subpath: 'skills/claude-handoff',
        reason: 'Specialized Claude session transition and summaries',
      },
    ],
  },
};
